 source 'http://rubygems.org'

gem 'rails', '3.2.11'
gem 'railties', ">=3.2.11"

group :production do
  gem 'pg'
end
group :development, :test do
  gem 'sqlite3'
end
gem 'execjs'
gem 'therubyracer'
gem 'thin'
gem 'heroku'
# Gem needed for parsing HTML in the protocol
gem "nokogiri", "~> 1.5.0"
# For password encryption
gem "bcrypt-ruby", :require => "bcrypt"

#gem "ruby-debug19"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'

group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
end
